### PR TITLE
Add random state for reproducibility

### PR DESCRIPTION
**Pull request by fnattino**
Addressing #46: In order to have reproducible simulation sampling in the store, we should have the possibility of seeding the random number generation. My impression is that the seeding is probably best introduced within `Bound`, so that one could do:
```python
bound = UnitCubeBound(n_parameters)
bound.set_seed(1234)
store.add(100, prior, bound)
store.add(100, prior, bound) # add more points following the previous stream of random numbers
```
The disadvantage is that one needs to instantiate the `Bound` object outside the store.   

Tasks:

- [x] code 
- [x] tests (?)
- [ ] tutorial notebooks

### CODE REVIEW

**Comment by fnattino** [comment]
Do you agree @bkmi ?

**Comment by bkmi** [comment]
I like what you propose, but I haven't groked how this may affect the new store definition. I suppose we should try to merge the new store specification first then incorporate this request?

I'm still thinking about instantiating the bound outside the store... I think it's okay because the "deepest" function which will generate the bounds is most likely [this one](https://github.com/undark-lab/swyft/blob/e4b36dc73247df4a9c507ac913b1debeef467da2/swyft/bounds.py#L332-L358)... 

Perhaps we can provide an option to give a current rng, then "split" it... I'm not sure about that yet. I'm not super comfortable with these new randomness generators.

**Comment by bkmi** [comment]
the notebooks from master have been brought into simplify now.

**Comment by fnattino** [comment]
(Thanks a lot @rogerkuou for continuing with this work which I had left halfway!)

>  Perhaps we can provide an option to give a current rng, then "split" it...

@bkmi  do you mean to provide the possibility to set a seeded rng in `Store` and then propagate this to all the calls to `pdf.sample()`? We could avoid storing rng as an attribute into the bound, but do something like:
```python
class Bound:
  ...
  def sample(self, n_samples, rng=None):
    rng = rng or np.random.default_rng()
    ...
  ...
```
In this way one would not need to seed the bound outside the store - one would seed the store instead. Also, the seeded rng in the store could be used to draw samples from the Poissonian [here](https://github.com/undark-lab/swyft/blob/09ba770196cfe54ee5f156a83dc826a6011222a7/swyft/store/store.py#L117) - which I had overlooked earlier - and which would still not be covered if we were to store rng in the bound..

**Comment by cweniger** [comment]
This is a pull request for v0.3, which is not actively developed. Closed for now, although the topic of reproducibility is relevant for v0.4 as well.

**Pull request closed without merging**
