### PR TITLE
Refactor directory/memory stores as single objects

### PR DESCRIPTION
**Pull request by fnattino**
Following #42, this PR refactors the memory/directory store classes as a single `Store` class, with the `memory_store` and `directory_store` factory methods to setup the two types of store. 

Tasks:
- [x] code
- [x] tests 
- [x] notebooks

### CODE REVIEW

**Comment by fnattino** [comment]
I have setup the `memory_store` and `directory_store` convenience functions to work as the previous initialisation functions of the Memory/DirectoryStore, with the functionality of the `load/save` methods left almost unaltered so:
* `Store.memory_store(simulator)` creates a new store based on Zarr MemoryStore.
* `Store.directory_store(path, simulator)` creates a new store or, if a store already exists at `path`, it opens it as a Zarr DirectoryStore.
* `Store.load(path)` loads an existing directory-based store into memory as a Zarr MemoryStore.
*  `store.save(path)` saves the `store` instance to disk:
    - If `store` is memory based, the Zarr store is converted to a DirectoryStore, at `path`;
    - If instead `store` is directory based, a new `store` instance is saved (potentially at a different path).


However, I think it might be cleaner to have:
* `Store.memory_store(simulator)` and `Store.directory_store(path, simulator)` only setting up new (empty) stores. 
* `Store.load(path)` (or maybe `Store.open(path)`?) to open an existing directory-based store as a Zarr DirectoryStore, so without loading the full dataset into memory.
* `store.save(path)` as above.
* an additional method (`store.to_memory_store()`?) to load the store into memory by converting the DirectoryStore to a MemoryStore (if it is not already such).

What are your thoughts on this @bkmi ?

**Comment by bkmi** [comment]
I like all of your suggestions.

I think having a load to memory pipeline which looks like this would be good:

```
store = Store.memory_store(simulator)
...
store.simulatre()
store.save(path)

...
copy_in_memory = Store.load(path).to_memory()
```

**Comment by fnattino** [comment]
Hey @bkmi, should be ready to review. Only need to update the simulator/store notebooks which have been merged to `master` - will do it as soon as this is merged.

**Review by bkmi — APPROVED** [review]
nice work. it looks really good.

**Pull request merged**
