### PR TITLE
Got rid of train_args and replaced it with explicit keywords arguments.

### LINKED ISSUE #31: Replace `train_args` with explicit training arguments
It is confusing to use train_args when training the network, since it is opaque what arguments are available. Make this explicit.

### PR DESCRIPTION
**Pull request by cweniger**
Closes #31

### CODE REVIEW

**Review by bkmi — CHANGES_REQUESTED** [review]
Having two copies of the same code (especially keyword arguments) is an antipattern. Consider trying to find the bug? If you overwrite a kwarg in your code, that is three places a value is defined. (in this case four because the function is wrapped twice.)

It was worse before but we can do better.

**Comment by bkmi** [comment]
I made the changes I liked along with blackend the code and isorted it, as should always be done.

**Review by bkmi — APPROVED** [review]

**Comment by bkmi** [comment]
The notebooks don't work due to other breaking changes in the past.

**Comment by cweniger** [comment]
Changes were/will be merged through master_dev

**Pull request closed without merging**
